GameZoneV1/Controllers/GamesController.cs
namespace GameZoneV1.Controllers
{
   
    public class GamesController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly ICategoriesService _categoriesService;
        private readonly IDevicesService _devicesService;
        private readonly IGamesService _gamesService;
        public GamesController(ApplicationDBContext context, ICategoriesService categoriesService ,
            IDevicesService devicesService, IGamesService gamesService)
        {
            _context = context;
            _categoriesService = categoriesService;
            _devicesService = devicesService;
            _gamesService = gamesService;
        }

        public IActionResult Index()
        {
            var games = _gamesService.GetAll();
            return View(games);
        }
        public IActionResult Details(int id)
        {
            var game = _gamesService.GetById(id);
            if (game==null)
            { 
                return NotFound();
                }
                return View(game);
        }
        [HttpGet]
        public IActionResult Create() 
        {
            CreateGameFromViewModel viewModel = new()
            {
                Categories = _categoriesService.GetSelectList(),
                Devices = _devicesService.GetSelectItems()
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFromViewModel newModel) 
        {
            if (!ModelState.IsValid)
            {
                newModel.Categories = _categoriesService.GetSelectList();
                newModel.Devices = _devicesService.GetSelectItems();
               return View(newModel);
            }

             await _gamesService.Create(newModel);
            return RedirectToAction(nameof(Index));  
        }
        [HttpGet]
        public IActionResult Edit(int id) 
        {
            var game = _gamesService.GetById(id);
            if(game==null) 
            return NotFound();
            
            EditViewModel viewModel = new()
            {
                Id = id,
                Name = game.Name,
                CategoryId = game.CategoryId,
                SelectedDevices = game.Devices.Select(d => d.DeviceId).ToList(),
                Categories = _categoriesService.GetSelectList(),
                Devices = _devicesService.GetSelectItems(),
                Description = game.Description,
                CurrentCover = game.Cover,
            };
            return View(viewModel) ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditViewModel model) 
        {
        if (!ModelState.IsValid) 
            {
                model.Categories = _categoriesService.GetSelectList();
                model.Devices = _devicesService.GetSelectItems();
                return View(model);
            }
            var game = await _gamesService.Edit(model);
            if(game==null) 
                return BadRequest();
            
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public IActionResult Delete(int id) 
        {
            var isDeleted = _gamesService.Delete(id);
            return isDeleted? Ok() : BadRequest();
        }
    }
}

GameZoneV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameZone | @ViewData["Title"]  </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZoneV1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />

</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-lg ">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                            @*<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Call_of_Duty_logo_2023.svg/1200px-Call_of_Duty_logo_2023.svg.png?20230727203218" alt="Call of Duty Logo">*@

                        </li>
                    </ul>
                    <ul class="navbar-nav">
                    @if (User.Identity!.IsAuthenticated == false)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="" asp-action="">Welcom @User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - GameZoneV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>